version: '3.8'

services:
  checkmk-cmk:
    container_name: checkmk-cmk
    image: ${IMAGE_NAME}
    pull_policy: never
    restart: unless-stopped
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - ${DATA_SOURCE_PATH}:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HOST_PORT}:5000
    networks:
      checkmk_network:

networks:
  checkmk_network: