# Developed by Antal Klemencsics, 2022 December
# The variables' values are imported from the .env file

version: '3.8'
name: 'checkmk-arm-stack'

services:
  site1:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}
    pull_policy: never
    restart: unless-stopped
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - ${DATA_SOURCE_PATH}:/omd/sites
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${HOST_PORT}:5000
    networks:
      common_network:

networks:
  common_network: